name = "template"
main = "src/worker.ts"
tsconfig = "./tsconfig.json"
compatibility_date = "2025-02-14"

[build]
command = "npm run build:frontend"
watch_dir = ["frontend"]

[assets]
directory = "frontend/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "strava-sync-db"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
