name = "template"
main = "src/worker.ts"
tsconfig = "./tsconfig.json"
compatibility_date = "2025-02-14"

[build]
command = "npm run build:frontend"
watch_dir = ["src", "frontend/src"]

[assets]
directory = "frontend/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "strava-sync"
database_id = "518ae258-2243-49ba-921c-fa249c9a3fdd"
